WITH ALLDATA AS (
	SELECT ORGID ID, PARENTID, NAME FROM ORG
  	UNION ALL
	SELECT ROLID ID, PARENTID, NAME FROM ROLE
  	UNION ALL
	SELECT EMPID ID, PARENTID, NAME  FROM EMPLOYEE
),
 DLOOP (ID, NAME, PARENTID, PATH, LEVEL) AS 
(
    SELECT ID, NAME, PARENTID, CAST(NAME as nvarchar(1000)) as PATH, 1 FROM ALLDATA
    UNION ALL
    SELECT B.ID, 
           B.NAME,
           B.PARENTID, 
  		   CAST(PATH + '/' + B.NAME as nvarchar(1000)) as PATH,
  		   LEVEL + 1
    FROM ALLDATA B
    INNER JOIN DLOOP AS A ON B.ParentID = A.ID
    AND B.ID <> 'ORG000'
), ORG_PATH AS (
SELECT A.* FROM DLOOP A
INNER JOIN
(SELECT ID, MAX(LEVEL) LEVEL FROM DLOOP
GROUP BY ID
) B
ON A.ID = B.ID AND A.LEVEL = B.LEVEL

), EMP_PATH AS (
SELECT * FROM ORG_PATH
where ID LIKE 'EMP%'
)
SELECT * FROM EMP_PATH